### ISSUE TITLE
Sign Up Form Doesn't Actually Track How Users Found Tweechable

### ISSUE THREAD

**Issue by vkoves** [Tweechable/tweechable_final#95] opened 2017-02-22 02:35 UTC
After making a sample account on PR #89, it seems that the how you found Tweechable information is not actually saved. This looks to be due to `registrations_controller.rb` not mentioning it as a permitted field, which is required for Devise custom fields.

Per @kevinpuj not in MVP

**Comment by McEileen** [comment] 2017-05-05 19:51
Hey, I was about to close this issue, but then I checked the heroku production database and saw that it says `nil` for the `how_found_tweechable` field for all of the users.  It doesn't seem to be tracking this field in production.  However, I checked my local database and it is tracking the `how_found_tweechable` field.  My local repo is up to date with the origin repo, so I'm not sure what the problem is..... I'll keep googling it and then close this issue after making a PR that actually fixes the problem.

**Comment by McEileen** [comment] 2017-05-09 02:44
Aha!  We hadn't deployed on heroku since before we accepted PR #99, which is why the heroku prod database still wasn't tracking the `how_found_tweechable` field.  I deployed yesterday and checked today with a new test user.  The prod database is successfully tracking the `how_found_tweechable` field, and I am consequently closing the issue.

**Closed by McEileen** 2017-05-09 02:44 UTC
Labels: bug
