### ISSUE TITLE
Can't log in, create account, reset password

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#102] opened 2017-03-15 01:28 UTC
SIGN UP / IN

To recreate:
https://tweechable.herokuapp.com/users/sign_up
Click "SIGN ME UP!" - I used kevinpuj+reportabug@gmail.com

After that, I get a view that doesn't appear  to be logged in (matches what I get in an incognito window, not signed in)

Even when I try signing in again, it's broken.

RESET PASSWORD

Also broken :(

**Comment by McEileen** [comment] 2017-05-02 02:29
Hi Kevin, I was able to successfully log in on the home page in production and see a different navbar than when I wasn't logged in, i.e., I saw a "logout" button but no "login" or "sign-up" button.  This matched what I expected.  

However, when I hit the "reset password" button, I never received an email to reset my password.  I THINK this is an error with sendgrid.  I also never received a confirmation email when I made a new account with my work email, and I had to log into the heroku database to manually confirm this new user account.  Again, I think sendgrid is broken, possibly dating back to when I changed the password for it.  I will investigate this tomorrow.

As for running the app locally, when I checked in rails console it said none of the three users in the seedfile were confirmed.  I was able to log in with them after tacking on `confirmed_at: Time.now` at the end of each `User.create(.....)` statement.  I saw the expected change in navbar functionality when I locally logged in with the seedfile users, both for the admin and the non-admin users.

The heroku prod db only has 11 users in it, and I'm guessing that it was wiped after you made and confirmed an account with your personal email.  Hence, you couldn't log in with that personal email. 
 When I checked the heroku prod db users associated with kevinpuj+reportabug@gmail.com and your personal email, neither account was confirmed.  I confirmed the two accounts and you should be able to log into our home page in prod now.  Please check and let me know.

For now, I think a toxic mix of the heroku prod database getting wiped and sendgrid breaking caused this error.  I'll let you know what I find after investigating sendgrid more.

**Comment by McEileen** [comment] 2017-05-05 19:01
I reset the sendgrid password today and then added it to heroku.  After that I was able to create a new account, confirm it with the sendgrid email, reset my password and then sign in with that new password.  Can someone please test this to confirm it and then close this issue?  I think we can also close issue #80.  I'm going to push up the tiny change I made in the seedfile, too.

Here is evidence from sendgrid's activity records below! :) . I blurred out the email address I used, but you can still see that it's me, heh.
<img width="649" alt="screen shot 2017-05-05 at 1 54 56 pm" src="https://cloud.githubusercontent.com/assets/5529982/25760210/5234f168-319b-11e7-96da-638b9630695a.png">

**Comment by McEileen** [comment] 2017-06-27 01:36
Today I re-confirmed the issue is fixed.  (See screenshot of activity records below.)  I'm closing the issue now.
<img width="938" alt="screen shot 2017-06-26 at 8 34 20 pm" src="https://user-images.githubusercontent.com/5529982/27567092-2b0e6fb4-5aaf-11e7-8319-743a644186c1.png">

**Closed by McEileen** 2017-06-27 01:36 UTC
Labels: bug
