### ISSUE TITLE
Make the Heroku app do things more frequently

### ISSUE THREAD

**Issue by kevinpuj** [Tweechable/tweechable_final#16] opened 2016-07-27 00:54 UTC
Right now, we have a ten minute wait.  What a cliffhanger!

**Comment by vkoves** [comment] 2016-10-05 03:51
Basically a duplicate of the [new issue](https://github.com/Tweechable/tweechable_final/issues/31) I made relating to moving over to a cron job for scheduling. Discussion can be continued there.

**Closed by vkoves** 2016-10-05 03:51 UTC
Labels: duplicate
